[package]
name = "idk"
version = "0.1.0"
authors = ["barloesgit <junhuitee@hotmail..com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix-web = "3"
actix = "0.10"
actix-web-actors = "3.0.0"
